spring:
  application:
    name: ecom-application
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: postgres
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
        ddl-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect